const express=require("express"), session=require("express-session"), bcrypt=require("bcryptjs"), Database=require("better-sqlite3"), path=require("path");
const app=express(), db=new Database("zipo.db");
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,phone TEXT,password TEXT NOT NULL,balance REAL DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS transactions(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,type TEXT,amount REAL,reference TEXT,status TEXT DEFAULT 'Pending',created_at TEXT DEFAULT CURRENT_TIMESTAMP);`);
app.use(express.json()); app.use(express.urlencoded({extended:true}));
app.use(session({secret:process.env.SESSION_SECRET||"change-this-secret",resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:"lax",secure:process.env.NODE_ENV==="production"}}));
app.use(express.static(path.join(__dirname,"public")));
const adminPass=process.env.DEVELOPER_PASS||"582301";
function auth(req,res,next){if(!req.session.user)return res.status(401).json({error:"Please log in"});next()}
function admin(req,res,next){if(!req.session.admin)return res.status(401).json({error:"Developer login required"});next()}
app.post("/api/register",(req,res)=>{let {name,email,phone,password}=req.body;if(!name||!email||!password)return res.status(400).json({error:"Name, email and password are required"});try{let hash=bcrypt.hashSync(password,12);let x=db.prepare("INSERT INTO users(name,email,phone,password) VALUES(?,?,?,?)").run(name,email,phone||"",hash);req.session.user={id:x.lastInsertRowid};res.json({ok:true})}catch(e){res.status(400).json({error:"Email is already registered"})}});
app.post("/api/login",(req,res)=>{let u=db.prepare("SELECT * FROM users WHERE email=?").get(req.body.email);if(!u||!bcrypt.compareSync(req.body.password,u.password))return res.status(401).json({error:"Invalid email or password"});req.session.user={id:u.id};res.json({ok:true})});
app.post("/api/developer-login",(req,res)=>{if(String(req.body.passcode)!==adminPass)return res.status(401).json({error:"Invalid developer passcode"});req.session.admin=true;res.json({ok:true})});
app.post("/api/logout",(req,res)=>req.session.destroy(()=>res.json({ok:true})));
app.get("/api/me",auth,(req,res)=>{let u=db.prepare("SELECT id,name,email,phone,balance,created_at FROM users WHERE id=?").get(req.session.user.id);let tx=db.prepare("SELECT * FROM transactions WHERE user_id=? ORDER BY id DESC").all(u.id);res.json({user:u,transactions:tx})});
app.put("/api/profile",auth,(req,res)=>{let {name,email,phone}=req.body;try{db.prepare("UPDATE users SET name=?,email=?,phone=? WHERE id=?").run(name,email,phone,req.session.user.id);res.json({ok:true})}catch(e){res.status(400).json({error:"Email may already be in use"})}});
app.post("/api/deposit",auth,(req,res)=>{let amount=Number(req.body.amount),reference=String(req.body.reference||"").trim();if(!(amount>0)||!reference)return res.status(400).json({error:"Enter a valid amount and Mpamba transaction reference"});db.prepare("INSERT INTO transactions(user_id,type,amount,reference,status) VALUES(?,?,?,?,?)").run(req.session.user.id,"Deposit",amount,reference,"Pending");res.json({ok:true,message:"Deposit submitted for verification"})});
app.post("/api/withdraw",auth,(req,res)=>{let amount=Number(req.body.amount),phone=String(req.body.phone||"").trim();let u=db.prepare("SELECT balance FROM users WHERE id=?").get(req.session.user.id);if(!(amount>0)||amount>u.balance||!phone)return res.status(400).json({error:"Invalid amount, phone number, or insufficient balance"});db.prepare("INSERT INTO transactions(user_id,type,amount,reference,status) VALUES(?,?,?,?,?)").run(req.session.user.id,"Withdrawal",amount,phone,"Pending");res.json({ok:true,message:"Withdrawal request submitted for review"})});
app.get("/api/admin/users",admin,(req,res)=>res.json(db.prepare("SELECT id,name,email,phone,balance,created_at FROM users ORDER BY id DESC").all()));
app.get("/api/admin/transactions",admin,(req,res)=>res.json(db.prepare("SELECT t.*,u.name,u.email FROM transactions t JOIN users u ON u.id=t.user_id ORDER BY t.id DESC").all()));
app.post("/api/admin/transactions/:id/approve",admin,(req,res)=>{let t=db.prepare("SELECT * FROM transactions WHERE id=?").get(req.params.id);if(!t||t.status!=="Pending")return res.status(400).json({error:"Transaction unavailable"});if(t.type==="Deposit")db.prepare("UPDATE users SET balance=balance+? WHERE id=?").run(t.amount,t.user_id);if(t.type==="Withdrawal"){let u=db.prepare("SELECT balance FROM users WHERE id=?").get(t.user_id);if(u.balance<t.amount)return res.status(400).json({error:"Insufficient user balance"});db.prepare("UPDATE users SET balance=balance-? WHERE id=?").run(t.amount,t.user_id)}db.prepare("UPDATE transactions SET status='Approved' WHERE id=?").run(t.id);res.json({ok:true})});
app.post("/api/admin/transactions/:id/reject",admin,(req,res)=>{db.prepare("UPDATE transactions SET status='Rejected' WHERE id=? AND status='Pending'").run(req.params.id);res.json({ok:true})});
app.listen(process.env.PORT||3000,()=>console.log("Zipo Earning running"));
